apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterPVmigrator
  labels:
    app: cpvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpvm
  template:
    metadata:
      labels:
        app: cpvm
    spec:
      containers:
      - name: cpvm
        image: quay.io/openshift/origin-cli:latest
        command:
          - bash
          - '-c'
          - >-
            yum install -y rsync curl && yum clean all -y &&
            mkdir -p /mnt/sourcepv /mnt/targetpv /mnt/scratch/{s,t}kube &&
            touch /mnt/scratch/{s,t}kube/KUBECONFIG &&
            oc login --token=${TGTTKN} --server=https://${OCPAPIURL}:{APIPORT} --kubeconfig=/mnt/scratch/tkube/KUBECONFIG &&
            oc project ${TPROJECT} 
            nohup tail -f /dev/null > /dev/null &
        env:
          - name: TGTTKN #target cluster token for oc to use
            value: 'need-token'
          - name: OCPAPIURL # target cluster token for oc to use (must provide)
            value: 'api.<api-url>'
          - name: APIPORT # port for target cluster's API (default 6443)
            value: '6443'
          - name: TPROJECT # target cluster project/ namespace
            value: '<project-name>'
        volumeMounts:
          - name: sourcepv
            mountPath: /mnt/sourcepv
          - name: scratchpv
            mountPath: /mnt/scratch
        volumes:
          - name: sourcepv
            persistentVolumeClaim:
             claimName: pvc-cpvm-source
          - name: scratchpv
            persistentVolumeClaim:
             claimName: pvc-cpvm-scratch
---
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: pvc-cpvm-source
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: azure-disk
    volumeMode: Filesystem
