apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpvm
  name: clusterpvmigrator
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cpvm
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cpvm
    spec:
      containers:
        - command:
            - bash
            - '-c'
            - >-
              mkdir -p /mnt/sourcepv /mnt/scratch/{s,t}kube && touch
              /mnt/scratch/{s,t}kube/KUBECONFIG && oc login --token=${TGTTKN}
              --server=https://${OCPAPIURL}:${APIPORT}
              --kubeconfig=/mnt/scratch/tkube/KUBECONFIG
              --insecure-skip-tls-verify=true && oc
              --kubeconfig=/mnt/scratch/tkube/KUBECONFIG
              --insecure-skip-tls-verify=true project ${TPROJECT} && tail -f
              /dev/null
          env:
            - name: TGTTKN
              value: <token here>
            - name: OCPAPIURL
              value: api.<ocpcluster-api-url-here>
            - name: APIPORT
              value: '6443'
            - name: TPROJECT
              value: <project-name>
          image: 'quay.io/openshift/origin-cli:latest'
          imagePullPolicy: Always
          name: cpvm
          resources: {}
          volumeMounts:
            - mountPath: /mnt/sourcepv
              name: sourcepv
            - mountPath: /mnt/scratch
              name: scratchpv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: sourcepv
          persistentVolumeClaim:
            claimName: pvc-cpvm-source
        - name: scratchpv
          persistentVolumeClaim:
            claimName: pvc-cpvm-scratch
