---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cpvm
  name: pvc-cpvm-scratch
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cpvm
  name: pvc-cpvm-source
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

