apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: "migrate-base-template"
  annotations:
    description: "Template to create a runnable pod intended to copy storage content from one PVC to another."
    tags: storage,migration
parameters:
- name: NAME
  description: "Name of the deployment config."
  value: "pvc-migration"
- name: SOURCE_PVC
  description: "Name of an existing PVC to use as the content source."
  required: true
- name: TARGET_PVC
  description: "Name of an existing PVC to use as the content target."
  required: true
- name: SLEEP_DURATION
  description: "Value for the sleep command to keep the migration pod alive."
  value: "1d"
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: pvc-migration
- name: SOURCE_IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: bcgov
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${NAME}
    labels:
      app: ${NAME}
  spec:
    replicas: 0
    revisionHistoryLimit: 3
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - env:
          - name: SLEEP
            value: ${SLEEP_DURATION}
          image: ""
          imagePullPolicy: Always
          name: ${NAME}
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /source
            name: source
          - mountPath: /target
            name: target
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: source
          persistentVolumeClaim:
            claimName: ${SOURCE_PVC}
        - name: target
          persistentVolumeClaim:
            claimName: ${TARGET_PVC}
    test: false
    triggers:
    - imageChangeParams:
        containerNames:
        - ${NAME}
        from:
          kind: ImageStreamTag
          name: ${SOURCE_IMAGE_NAME}:${TAG_NAME}
          namespace: ${SOURCE_IMAGE_NAMESPACE}
      type: ImageChange